AWSTemplateFormatVersion: "2010-09-09"

Resources:
  # Front End (S3 + CloudFront)
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

Outputs:
  ArtifactBucketName:
    Value: !Ref ArtifactBucket