AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31


Resources:
  # Front End (S3 + CloudFront)
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AWS::StackName}-oac"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html

        Origins:
          - Id: FrontendS3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            OriginAccessControlId: !Ref CloudFrontOriginAccessControl
            S3OriginConfig: {}

        DefaultCacheBehavior:
          TargetOriginId: FrontendS3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
  
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy 
    Properties:
      Bucket: !Ref FrontendBucket 
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${FrontendBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub
                  - "arn:aws:cloudfront::${AWS::AccountId}:distribution/${DistributionId}"
                  - DistributionId: !Ref CloudFrontDistribution

  # Lambdas
  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/lambdas
      Handler: health.handler
      Runtime: python3.12
      Events:
        Health:
          Type: HttpApi
          Properties:
            Path: /health
            Method: GET

Outputs:
  FrontendBucketName:
    Value: !Ref FrontendBucket

  CloudFrontDistributionId:
    Value: !Ref CloudFrontDistribution

  FrontendUrl:
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"

  HealthFunctionUrl:
    Description: Health check endpoint
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/health"