AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31


Resources:
  # Front End (S3 + CloudFront)
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AWS::StackName}-oac"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html

        Origins:
          - Id: FrontendS3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            OriginAccessControlId: !Ref CloudFrontOriginAccessControl
            S3OriginConfig: {}

        DefaultCacheBehavior:
          TargetOriginId: FrontendS3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
  
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy 
    Properties:
      Bucket: !Ref FrontendBucket 
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub "${FrontendBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub
                  - "arn:aws:cloudfront::${AWS::AccountId}:distribution/${DistributionId}"
                  - DistributionId: !Ref CloudFrontDistribution


  # Eranova Gateway
  EranovaApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "*"
        AllowMethods:
          - GET
          - POST
          
  # Lambdas
  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/
      Handler: lambdas.health.handler
      Runtime: python3.12
      Events:
        Health:
          Type: HttpApi
          Properties:
            ApiId: !Ref EranovaApi
            Path: /health
            Method: GET
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref InvoicesBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref InvoicesMetadataTable
        - DynamoDBCrudPolicy:
            TableName: !Ref InvoiceExtractionsTable
      Environment:
        Variables:
          INVOICES_BUCKET: !Ref InvoicesBucket
          INVOICE_METADATA_TABLE: !Ref InvoicesMetadataTable
          INVOICE_EXTRACTIONS_TABLE: !Ref InvoiceExtractionsTable

  CreateInvoiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/
      Handler: lambdas.create_invoice.handler
      Runtime: python3.12

      Events:
        CreateInvoice:
          Type: HttpApi
          Properties:
            ApiId: !Ref EranovaApi
            Path: /invoices
            Method: POST

      Policies:
        - S3CrudPolicy:
            BucketName: !Ref InvoicesBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref InvoicesMetadataTable

      Environment:
        Variables:
          INVOICES_BUCKET: !Ref InvoicesBucket
          INVOICE_METADATA_TABLE: !Ref InvoicesMetadataTable


  ListInvoicesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/
      Handler: lambdas.list_invoices.handler
      Runtime: python3.12

      Events:
        ListInvoices:
          Type: HttpApi
          Properties:
            ApiId: !Ref EranovaApi
            Path: /invoices
            Method: GET

      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref InvoicesMetadataTable

      Environment:
        Variables:
          INVOICE_METADATA_TABLE: !Ref InvoicesMetadataTable


  GetInvoiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../backend/
      Handler: lambdas.get_invoice.handler
      Runtime: python3.12

      Events:
        GetInvoice:
          Type: HttpApi
          Properties:
            ApiId: !Ref EranovaApi
            Path: /invoices/{invoice_id}
            Method: GET

      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref InvoicesMetadataTable

      Environment:
        Variables:
          INVOICE_METADATA_TABLE: !Ref InvoicesMetadataTable


  # Storage - S3 For Invoices, Dynamo for Metadata Tables + Extraction Documents
  InvoicesBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

  InvoicesMetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: invoice_id
          AttributeType: S
      KeySchema:
        - AttributeName: invoice_id
          KeyType: HASH

  InvoiceExtractionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: extraction_id
          AttributeType: S
      KeySchema:
        - AttributeName: extraction_id
          KeyType: HASH

Outputs:
  FrontendBucketName:
    Value: !Ref FrontendBucket

  CloudFrontDistributionId:
    Value: !Ref CloudFrontDistribution

  FrontendUrl:
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"

  HealthFunctionUrl:
    Description: Health check endpoint
    Value: !Sub "https://${EranovaApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/health"