name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Deploy Artifact Bucket
        run: | 
          aws cloudformation deploy \
            --template-file infra/artifact-bucket-template.yaml \
            --stack-name eranova-takehome-artifact-bucket

      - name: Get artifact bucket
        run: |
          ARTIFACT_BUCKET=$(aws cloudformation describe-stacks \
            --stack-name eranova-takehome-artifact-bucket \
            --query "Stacks[0].Outputs[?OutputKey=='ArtifactBucketName'].OutputValue" \
            --output text)

          echo "ARTIFACT_BUCKET=$ARTIFACT_BUCKET" >> $GITHUB_ENV
      
      - name: Package infrastructure
        run: |
          aws cloudformation package \
            --template-file infra/template.yaml \
            --s3-bucket $ARTIFACT_BUCKET \
            --output-template-file packaged-template.yaml

      - name: Deploy infrastructure
        run: | 
          aws cloudformation deploy \
            --template-file packaged-template.yaml \
            --stack-name eranova-takehome \
            --capabilities CAPABILITY_IAM

      - name: Build frontend
        working-directory: frontend
        run: | 
          npm ci 
          npm run build 

      - name: Get infrastructure outputs
        run: |
          BUCKET=$(aws cloudformation describe-stacks \
            --stack-name eranova-takehome \
            --query "Stacks[0].Outputs[?OutputKey=='FrontendBucketName'].OutputValue" \
            --output text)

          DISTRIBUTION=$(aws cloudformation describe-stacks \
            --stack-name eranova-takehome \
            --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDistributionId'].OutputValue" \
            --output text)

          echo "BUCKET=$BUCKET" >> $GITHUB_ENV
          echo "DISTRIBUTION=$DISTRIBUTION" >> $GITHUB_ENV

      - name: Upload frontend
        run: aws s3 sync frontend/out/ s3://$BUCKET --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $DISTRIBUTION \
            --paths "/*"